name: Publish Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
      release_name:
        description: 'Release name'
        required: true

# Permissions are required to create a Release.
permissions:
  contents: write
  actions: read
  
jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install 7-Zip
      shell: cmd
      run: |
        choco install 7zip -y
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    # Run dotnet as a publish step so we can make single-file.
    # publish has some new bug, so we need to use .csproj as target
    - name: Publish
      run: dotnet publish --output "./" --runtime win10-x64 --configuration Release  -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true 3DV_Installer.csproj
    
    # Unzip the NVidia 3D Vision Driver installer, so that it does not need to exist at launch.
    - name: Unzip 3DVision.exe
      run: 7z x .\NVidia\3DVision.Exe "-o.\3DVisionDriver" -y
      
    # Use 7z to zip up entire package for better compression.
    # '3DVisionDriver\' will take all items and keep folder name.
    # 'Extras\' will take both resource.dat and rcedit.exe and keep folder name.
    - name: 7z all
      run: 7z a .\3DV_Installer.7z 3DVisionDriver\ Extras\ .\3DV_installer.exe
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: ${{ github.event.inputs.release_name }}
        files: |
          3DV_Installer.7z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
